// Generated by CoffeeScript 1.6.3
(function() {
  var ORM, activityInsert, apiAuth, apiVerifyObjectProperties, async, config, insertHelper, sequelize, uuid, _;

  _ = require('underscore');

  async = require('async');

  uuid = require('node-uuid');

  config = require(GLOBAL.appRoot + 'config/config');

  apiVerifyObjectProperties = require(GLOBAL.appRoot + 'components/apiVerifyObjectProperties');

  apiAuth = require(GLOBAL.appRoot + 'components/apiAuth');

  ORM = require(GLOBAL.appRoot + 'components/oRM');

  activityInsert = require(GLOBAL.appRoot + 'components/activityInsert');

  insertHelper = require(GLOBAL.appRoot + 'components/insertHelper');

  sequelize = ORM.setup();

  module.exports = function(app) {
    var client, dictionary, employee;
    employee = ORM.model('employee');
    client = ORM.model('client');
    dictionary = ORM.model('dictionary');
    return app.post(config.apiSubDir + '/v1/dictionaries', function(req, res) {
      return async.series([
        function(callback) {
          return apiAuth(req, res, callback);
        }, function(callback) {
          var clientUid, employeeUid, insertMethod, userType;
          userType = req.session.user.type;
          clientUid = req.session.user.clientUid;
          employeeUid = req.session.user.uid;
          switch (userType) {
            case 'superAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, dictionary, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'name': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        return callback(null, {
                          success: false,
                          message: {
                            name: 'required'
                          }
                        });
                      }
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      var testClientUid;
                      testClientUid = !_.isUndefined(object['clientUid']) ? object['clientUid'] : clientUid;
                      return client.find({
                        where: {
                          uid: testClientUid
                        }
                      }).success(function(resultClient) {
                        var mapObj;
                        if (resultClient) {
                          mapObj = {};
                          mapObj[resultClient.uid] = resultClient;
                          return callback(null, {
                            success: true,
                            transform: [objectKey, 'clientUid', resultClient.uid],
                            uidMapping: mapObj
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              clientUid: 'unknown'
                            }
                          });
                        }
                      });
                    }
                  }
                }, function(objects) {
                  return insertHelper('dictionaries', clientUid, dictionary, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return callback(null, createdUid);
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body);
              }
              break;
            case 'clientSuperAdmin':
            case 'clientAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, dictionary, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'name': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        return callback(null, {
                          success: false,
                          message: {
                            name: 'required'
                          }
                        });
                      }
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      var testClientUid;
                      if (!_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            clientUid: 'unknown'
                          }
                        });
                        return;
                      }
                      testClientUid = clientUid;
                      return client.find({
                        where: {
                          uid: testClientUid
                        }
                      }).success(function(resultClient) {
                        var mapObj;
                        mapObj = {};
                        mapObj[resultClient.uid] = resultClient;
                        return callback(null, {
                          success: true,
                          transform: [objectKey, 'clientUid', resultClient.uid],
                          uidMapping: mapObj
                        });
                      });
                    }
                  }
                }, function(objects) {
                  return insertHelper('dictionaries', clientUid, dictionary, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return callback(null, createdUid);
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body, function(uid) {
                  if (_.isString(uid) && _.isUndefined(uid.code)) {
                    config.apiSuccessPostResponse(res, uid);
                    return activityInsert({
                      type: 'createDictionary',
                      dictionaryUid: uid,
                      employeeUid: employeeUid,
                      clientUid: clientUid
                    }, app, req);
                  } else {
                    return res.jsonAPIRespond(uid);
                  }
                });
              }
              break;
            case 'clientDelegate':
            case 'clientAuditor':
              return res.jsonAPIRespond(config.errorResponse(401));
          }
        }
      ]);
    });
  };

}).call(this);
