// Generated by CoffeeScript 1.6.3
(function() {
  var SEQ, orm;

  orm = require(GLOBAL.appRoot + 'components/oRM');

  SEQ = orm.SEQ;

  module.exports = {
    model: {
      id: SEQ.INTEGER,
      name: {
        type: SEQ.STRING,
        validate: {
          len: [5, 100]
        }
      },
      type: SEQ.ENUM('full', 'mini'),
      clientUid: {
        type: SEQ.STRING,
        validate: {
          isUUID: 4,
          notNull: true
        }
      },
      employeeUid: {
        type: SEQ.STRING,
        validate: {
          isUUID: 4,
          notNull: true
        }
      }
    },
    relations: [
      {
        relation: 'belongsTo',
        model: 'client'
      }, {
        relation: 'hasMany',
        model: 'revision'
      }
    ],
    options: {
      paranoid: true
    }
  };

}).call(this);
