// Generated by CoffeeScript 1.6.3
(function() {
  var ORM, apiAuth, apiVerifyObjectProperties, async, bcrypt, config, sequelize, updateHelper, uuid, _;

  _ = require('underscore');

  async = require('async');

  bcrypt = require('bcrypt');

  uuid = require('node-uuid');

  config = require(GLOBAL.appRoot + 'config/config');

  apiVerifyObjectProperties = require(GLOBAL.appRoot + 'components/apiVerifyObjectProperties');

  apiAuth = require(GLOBAL.appRoot + 'components/apiAuth');

  ORM = require(GLOBAL.appRoot + 'components/oRM');

  updateHelper = require(GLOBAL.appRoot + 'components/updateHelper');

  sequelize = ORM.setup();

  module.exports = function(app) {
    var client, employee;
    client = ORM.model('client');
    employee = ORM.model('employee');
    return app.put(config.apiSubDir + '/v1/employees', function(req, res) {
      return async.series([
        function(callback) {
          return apiAuth(req, res, callback);
        }, function(callback) {
          var clientUid, userType;
          userType = req.session.user.type;
          clientUid = req.session.user.clientUid;
          switch (userType) {
            case 'superAdmin':
              return apiVerifyObjectProperties(this, employee, req.body, req, res, false, {
                requiredProperties: {
                  'uid': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      return callback(null, {
                        success: false,
                        message: {
                          uid: 'required'
                        }
                      });
                    } else {
                      return employee.find({
                        where: {
                          uid: val
                        }
                      }).success(function(resultEmployee) {
                        var mapObj;
                        if (resultEmployee) {
                          mapObj = {};
                          mapObj[val] = resultEmployee;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              uid: 'unknown'
                            }
                          });
                        }
                      });
                    }
                  },
                  'identifier': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        uid: object['uid']
                      }
                    }).success(function(resultEmployee) {
                      return employee.find({
                        where: {
                          identifier: val,
                          clientUid: resultEmployee.clientUid
                        }
                      }).success(function(resultEmployee) {
                        if (resultEmployee && resultEmployee.uid !== object['uid']) {
                          return callback(null, {
                            success: false,
                            message: {
                              identifier: 'duplicate'
                            }
                          });
                        } else {
                          return callback(null, {
                            success: true
                          });
                        }
                      });
                    });
                  },
                  'firstName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'lastName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'email': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'phone': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'username': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        uid: object['uid']
                      }
                    }).success(function(resultEmployee) {
                      return employee.find({
                        where: {
                          username: val,
                          clientUid: resultEmployee.clientUid
                        }
                      }).success(function(resultEmployee) {
                        if (resultEmployee && resultEmployee.uid !== object['uid']) {
                          return callback(null, {
                            success: false,
                            message: {
                              username: 'duplicate'
                            }
                          });
                        } else {
                          return callback(null, {
                            success: true
                          });
                        }
                      });
                    });
                  },
                  'password': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val) || val.length > 100) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return bcrypt.genSalt(10, function(err, salt) {
                      return bcrypt.hash(val, salt, function(err, hash) {
                        return callback(null, {
                          success: false,
                          transform: [object, 'password', hash]
                        });
                      });
                    });
                  },
                  'type': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: false
                    });
                  }
                }
              }, function(objects) {
                return updateHelper(employee, objects, req, res, app);
              });
            case 'clientSuperAdmin':
              return apiVerifyObjectProperties(this, employee, req.body, req, res, false, {
                requiredProperties: {
                  'uid': function(val, objectKey, object, callback) {
                    console.log('val');
                    console.log(val);
                    if (_.isUndefined(val)) {
                      return callback(null, {
                        success: false,
                        message: {
                          uid: 'required'
                        }
                      });
                    } else {
                      return employee.find({
                        where: {
                          uid: val
                        }
                      }).success(function(resultEmployee) {
                        var mapObj;
                        if (resultEmployee) {
                          mapObj = {};
                          mapObj[val] = resultEmployee;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              uid: 'unknown'
                            }
                          });
                        }
                      });
                    }
                  },
                  'identifier': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        clientUid: clientUid,
                        identifier: val
                      }
                    }).success(function(resultEmployee) {
                      if (resultEmployee && resultEmployee.uid !== object['uid']) {
                        return callback(null, {
                          success: false,
                          message: {
                            identifier: 'duplicate'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    });
                  },
                  'firstName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'lastName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'email': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'phone': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'username': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        clientUid: clientUid,
                        username: val
                      }
                    }).success(function(resultEmployee) {
                      if (resultEmployee && resultEmployee.uid !== object['uid']) {
                        return callback(null, {
                          success: false,
                          message: {
                            username: 'duplicate'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    });
                  },
                  'password': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val) || val.length > 100) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return bcrypt.genSalt(10, function(err, salt) {
                      return bcrypt.hash(val, salt, function(err, hash) {
                        return callback(null, {
                          success: false,
                          transform: [object, 'password', hash]
                        });
                      });
                    });
                  },
                  'type': function(val, objectKey, object, callback) {
                    if (val === 'superAdmin') {
                      callback(null, {
                        success: false,
                        message: {
                          type: 'invalid'
                        }
                      });
                      return;
                    }
                    return callback(null, {
                      success: false
                    });
                  }
                }
              }, function(objects) {
                return updateHelper(employee, objects, req, res, app);
              });
            case 'clientAdmin':
              return apiVerifyObjectProperties(this, employee, req.body, req, res, false, {
                requiredProperties: {
                  'uid': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      return callback(null, {
                        success: false,
                        message: {
                          uid: 'required'
                        }
                      });
                    } else {
                      return employee.find({
                        where: {
                          uid: val
                        }
                      }).success(function(resultEmployee) {
                        var mapObj;
                        if (resultEmployee) {
                          mapObj = {};
                          mapObj[val] = resultEmployee;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              uid: 'unknown'
                            }
                          });
                        }
                      });
                    }
                  },
                  'identifier': function(val, objectKey, object, callback) {
                    if (_.isUndefined(username)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        clientUid: clientUid,
                        identifier: val
                      }
                    }).success(function(resultEmployee) {
                      if (resultEmployee && resultEmployee.uid !== object['uid']) {
                        return callback(null, {
                          success: false,
                          message: {
                            identifier: 'duplicate'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    });
                  },
                  'firstName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'lastName': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'email': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'phone': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'username': function(val, objectKey, object, callback) {
                    if (_.isUndefined(username)) {
                      callback(null, {
                        success: true
                      });
                      return;
                    }
                    if (_.isUndefined(object['uid'])) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return employee.find({
                      where: {
                        clientUid: clientUid,
                        username: val
                      }
                    }).success(function(resultEmployee) {
                      if (resultEmployee && resultEmployee.uid !== object['uid']) {
                        return callback(null, {
                          success: false,
                          message: {
                            username: 'duplicate'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    });
                  },
                  'password': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val) || val.length > 100) {
                      callback(null, {
                        success: false
                      });
                      return;
                    }
                    return bcrypt.genSalt(10, function(err, salt) {
                      return bcrypt.hash(val, salt, function(err, hash) {
                        return callback(null, {
                          success: false,
                          transform: [object, 'password', hash]
                        });
                      });
                    });
                  },
                  'type': function(val, objectKey, object, callback) {
                    if (val === 'superAdmin' || val === 'clientSuperAdmin') {
                      callback(null, {
                        success: false,
                        message: {
                          type: 'invalid'
                        }
                      });
                      return;
                    }
                    return callback(null, {
                      success: true
                    });
                  }
                }
              }, function(objects) {
                return updateHelper(employee, objects, req, res, app);
              });
            case 'clientDelegate':
            case 'clientAuditor':
              return res.jsonAPIRespond(config.errorResponse(401));
          }
        }
      ]);
    });
  };

}).call(this);
