// Generated by CoffeeScript 1.6.3
(function() {
  var ORM, apiAuth, apiVerifyObjectProperties, async, config, insertHelper, sequelize, uuid, _;

  _ = require('underscore');

  async = require('async');

  uuid = require('node-uuid');

  config = require(GLOBAL.appRoot + 'config/config');

  apiVerifyObjectProperties = require(GLOBAL.appRoot + 'components/apiVerifyObjectProperties');

  apiAuth = require(GLOBAL.appRoot + 'components/apiAuth');

  insertHelper = require(GLOBAL.appRoot + 'components/insertHelper');

  ORM = require(GLOBAL.appRoot + 'components/oRM');

  sequelize = ORM.setup();

  module.exports = function(app) {
    var client, employee, group, revision, template;
    template = ORM.model('template');
    employee = ORM.model('employee');
    client = ORM.model('client');
    revision = ORM.model('revision');
    group = ORM.model('group');
    return app.post(config.apiSubDir + '/v1/templates', function(req, res) {
      return async.series([
        function(callback) {
          return apiAuth(req, res, callback);
        }, function(callback) {
          var clientUid, insertChildRevisionAndGroupHelper, insertMethod, uid, userType;
          userType = req.session.user.type;
          clientUid = req.session.user.clientUid;
          uid = req.session.user.uid;
          insertChildRevisionAndGroupHelper = function(uid, completeCallback) {
            return template.find({
              where: {
                uid: uid
              }
            }).success(function(resultTemplate) {
              return revision.create({
                uid: uuid.v4(),
                changeSummary: '',
                scope: '',
                finalized: false,
                clientUid: resultTemplate.clientUid,
                templateUid: resultTemplate.uid,
                employeeUid: resultTemplate.employeeUid,
                clientId: resultTemplate.clientId,
                templateId: resultTemplate.id,
                employeeId: resultTemplate.employeeId
              }).success(function(resultRevision) {
                return group.create({
                  uid: uuid.v4(),
                  name: 'First Exercise Group',
                  description: '',
                  ordinal: 0,
                  clientUid: resultRevision.clientUid,
                  revisionUid: resultRevision.uid,
                  clientId: resultRevision.clientId,
                  revisionId: resultRevision.id
                }).success(function(resultGroup) {
                  return completeCallback(uid);
                });
              });
            });
          };
          switch (userType) {
            case 'superAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, template, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'name': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        return callback(null, {
                          success: false,
                          message: {
                            name: 'required'
                          }
                        });
                      }
                    },
                    'type': function(val, objectKey, object, callback) {
                      if (val) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        return callback(null, {
                          success: true,
                          transform: [objectKey, 'type', 'full']
                        });
                        /*
                        callback null,
                          success: false
                          message:
                            type: 'required'
                        */

                      }
                    },
                    'employeeUid': function(val, objectKey, object, callback) {
                      var testClientUid;
                      if (!val) {
                        callback(null, {
                          success: false,
                          message: {
                            employeeUid: 'required'
                          }
                        });
                        return;
                      }
                      testClientUid = !_.isUndefined(object['clientUid']) ? object['clientUid'] : clientUid;
                      return async.parallel([
                        function(callback) {
                          return client.find({
                            where: {
                              uid: testClientUid
                            }
                          }).success(function(resultClient) {
                            return callback(null, resultClient);
                          });
                        }, function(callback) {
                          return employee.find({
                            where: {
                              uid: val
                            }
                          }).success(function(resultEmployee) {
                            return callback(null, resultEmployee);
                          });
                        }
                      ], function(error, results) {
                        var mapObj, resultClient, resultEmployee;
                        resultClient = results[0];
                        resultEmployee = results[1];
                        if (!resultEmployee) {
                          callback(null, {
                            success: false,
                            message: {
                              'employeeUid': 'unknown'
                            }
                          });
                          return;
                        }
                        if (!resultClient) {
                          callback(null, {
                            success: false,
                            'clientUid': 'unknown'
                          });
                          return;
                        }
                        if (resultEmployee.clientUid !== resultClient.uid) {
                          callback(null, {
                            success: false,
                            message: {
                              'employeeUid': 'unknown'
                            }
                          });
                          return;
                        }
                        mapObj = {};
                        mapObj[resultEmployee.uid] = resultEmployee;
                        mapObj[resultClient.uid] = resultClient;
                        return callback(null, {
                          success: true,
                          uidMapping: mapObj,
                          transform: [objectKey, 'clientUid', resultClient.uid]
                        });
                      });
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      callback(null, {
                        success: true
                      });
                    }
                  }
                }, function(objects) {
                  return insertHelper('templates', clientUid, template, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return insertChildRevisionAndGroupHelper(createdUid, function(uid) {
                      return callback(null, uid);
                    });
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body, function(uid) {
                  if (_.isString(uid) && _.isUndefined(uid.code)) {
                    return insertChildRevisionAndGroupHelper(uid, function(uid) {
                      return config.apiSuccessPostResponse(res, uid);
                    });
                  } else {
                    return res.jsonAPIRespond(uid);
                  }
                });
              }
              break;
            case 'clientSuperAdmin':
            case 'clientAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, template, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'name': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        return callback(null, {
                          success: false,
                          message: {
                            name: 'required'
                          }
                        });
                      }
                    },
                    'type': function(val, objectKey, object, callback) {
                      if (val) {
                        return callback(null, {
                          success: true
                        });
                      } else {
                        val = 'full';
                        return callback(null, {
                          success: true,
                          transform: [objectKey, 'type', 'full']
                        });
                        /*
                        callback null,
                          success: false
                          message:
                            type: 'required'
                        */

                      }
                    },
                    'employeeUid': function(val, objectKey, object, callback) {
                      var where;
                      if (_.isUndefined(val)) {
                        val = uid;
                      }
                      where = {
                        uid: val,
                        clientUid: clientUid
                      };
                      return employee.find({
                        where: where
                      }).success(function(resultEmployee) {
                        var mapObj;
                        if (resultEmployee) {
                          mapObj = {};
                          mapObj[resultEmployee.uid] = resultEmployee;
                          return callback(null, {
                            uidMapping: mapObj,
                            success: true,
                            transform: [objectKey, 'employeeUid', resultEmployee.uid]
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              employeeUid: 'unknown'
                            }
                          });
                        }
                      });
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            clientUid: 'unknown'
                          }
                        });
                      } else {
                        return client.find({
                          where: {
                            uid: clientUid
                          }
                        }).success(function(resultClient) {
                          var mapObj;
                          mapObj = {};
                          mapObj[resultClient.uid] = resultClient;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj,
                            transform: [objectKey, 'clientUid', clientUid]
                          });
                        });
                      }
                    }
                  }
                }, function(objects) {
                  return insertHelper('templates', clientUid, template, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return insertChildRevisionAndGroupHelper(createdUid, function(uid) {
                      return callback(null, uid);
                    });
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body, function(uid) {
                  if (_.isString(uid) && _.isUndefined(uid.code)) {
                    return insertChildRevisionAndGroupHelper(uid, function(uid) {
                      return config.apiSuccessPostResponse(res, uid);
                    });
                  } else {
                    return res.jsonAPIRespond(uid);
                  }
                });
              }
              break;
            case 'clientDelegate':
            case 'clientAuditor':
              return res.jsonAPIRespond(config.errorResponse(401));
          }
        }
      ]);
    });
  };

}).call(this);
