// Generated by CoffeeScript 1.6.3
(function() {
  var ORM, apiAuth, apiVerifyObjectProperties, async, config, sequelize, updateHelper, uuid, _;

  _ = require('underscore');

  async = require('async');

  uuid = require('node-uuid');

  config = require(GLOBAL.appRoot + 'config/config');

  apiVerifyObjectProperties = require(GLOBAL.appRoot + 'components/apiVerifyObjectProperties');

  apiAuth = require(GLOBAL.appRoot + 'components/apiAuth');

  ORM = require(GLOBAL.appRoot + 'components/oRM');

  updateHelper = require(GLOBAL.appRoot + 'components/updateHelper');

  sequelize = ORM.setup();

  module.exports = function(app) {
    var client;
    client = ORM.model('client');
    return app.put(config.apiSubDir + '/v1/clients', function(req, res) {
      return async.series([
        function(callback) {
          return apiAuth(req, res, callback);
        }, function(callback) {
          var clientUid, userType;
          userType = req.session.user.type;
          clientUid = req.session.user.clientUid;
          switch (userType) {
            case 'superAdmin':
              return apiVerifyObjectProperties(this, client, req.body, req, res, false, {
                requiredProperties: {
                  'uid': function(val, objectKey, object, callback) {
                    if (_.isUndefined(val)) {
                      return callback(null, {
                        success: false,
                        message: {
                          uid: 'required'
                        }
                      });
                    } else {
                      return client.find({
                        where: {
                          uid: val
                        }
                      }).success(function(resultClient) {
                        var mapObj;
                        if (resultClient) {
                          mapObj = {};
                          mapObj[val] = resultClient;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj
                          });
                        } else {
                          return callback(null, {
                            success: false,
                            message: {
                              uid: 'unknown'
                            }
                          });
                        }
                      });
                    }
                  },
                  'name': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'identifier': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'address1': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'address2': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'address3': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'city': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'stateProvince': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'country': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'telephone': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'fax': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'businessDivision0Name': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'businessDivision1Name': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  },
                  'businessDivision2Name': function(val, objectKey, object, callback) {
                    return callback(null, {
                      success: true
                    });
                  }
                }
              }, function(objects) {
                return updateHelper(client, objects, req, res, app);
              });
            case 'clientSuperAdmin':
            case 'clientAdmin':
            case 'clientDelegate':
            case 'clientAuditor':
              return res.jsonAPIRespond(config.errorResponse(401));
          }
        }
      ]);
    });
  };

}).call(this);
