// Generated by CoffeeScript 1.6.3
(function() {
  var config, _;

  _ = require('underscore');

  config = require(GLOBAL.appRoot + 'config/config');

  module.exports = function(req, res, callback) {
    if (req.requestType === 'http') {
      if (req.session.user == null) {
        return res.jsonAPIRespond(config.errorResponse(401));
      } else if (config.authCategories.indexOf(req.session.user.type) === -1) {
        return res.jsonAPIRespond(config.errorResponse(401));
      } else {
        return callback();
      }
    } else if (req.requestType === 'socketio') {
      if (req.session.user == null) {
        return res.jsonAPIRespond(config.errorResponse(401));
      } else if (config.authCategories.indexOf(req.session.user.type) === -1) {
        return res.jsonAPIRespond(config.errorResponse(401));
      } else {
        return callback();
      }
    } else {
      throw new Error();
    }
  };

}).call(this);
