// Generated by CoffeeScript 1.6.3
(function() {
  var async, config, _;

  async = require('async');

  _ = require('underscore');

  config = require(GLOBAL.appRoot + 'config/config');

  module.exports = function(resource, conditions, res) {
    return resource.findAll({
      where: conditions
    }).success(function(resources) {
      var deletedItems;
      deletedItems = [];
      return async.map(resources, function(item, callback) {
        if (_.isNull(item.deletedAt)) {
          deletedItems.push(item.uid);
        }
        return item.destroy().success(function() {
          if (!_.isUndefined(app.io) && _.isFunction(app.io.room)) {
            app.io.room(item.uid).broadcast('resourcePut', {
              apiCollectionName: '',
              resourceName: resource.name,
              resource: JSON.parse(JSON.stringify(item))
            });
          }
          return callback();
        });
      }, function() {
        return res.jsonAPIRespond(_.extend({
          code: 202,
          message: config.apiResponseCodes[202]
        }, {
          deletedItems: deletedItems
        }));
      });
    });
  };

}).call(this);
