// Generated by CoffeeScript 1.6.3
(function() {
  var async, config, _;

  _ = require('underscore');

  async = require('async');

  config = require(GLOBAL.appRoot + 'config/config');

  module.exports = function(resourceModel, objects, requirements) {
    var errorObj, exceptionProperties, key, object, objectPropertyKey, objectPropertyValue, unknownProperties, _i, _len;
    unknownProperties = [];
    for (key = _i = 0, _len = objects.length; _i < _len; key = ++_i) {
      object = objects[key];
      for (objectPropertyKey in object) {
        objectPropertyValue = object[objectPropertyKey];
        if (_.isUndefined(requirements.requiredProperties[objectPropertyKey])) {
          exceptionProperties = config.resourceModelUnknownFieldsExceptions[resourceModel.name];
          if (_.isUndefined(exceptionProperties) || (exceptionProperties.indexOf(objectPropertyKey) === -1)) {
            errorObj = {};
            errorObj[objectPropertyKey] = 'unknown field';
            unknownProperties.push(errorObj);
          }
        }
      }
    }
    return unknownProperties;
  };

}).call(this);
