// Generated by CoffeeScript 1.6.3
(function() {
  var config, createClient, createStore, express, redis, redisStore;

  redis = require('redis');

  express = require('express.io');

  redisStore = require('connect-redis')(express);

  config = require(GLOBAL.appRoot + 'config/config');

  createClient = function() {
    var client;
    client = redis.createClient(config.redis.port, config.redis.host);
    client.auth(config.redis.pass, function() {});
    return client;
  };

  createStore = function() {
    var store;
    return store = new redisStore(config.redis);
  };

  module.exports = {
    createClient: createClient,
    createStore: createStore
  };

}).call(this);
