// Generated by CoffeeScript 1.6.3
(function() {
  var config, _;

  _ = require('underscore');

  config = require(GLOBAL.appRoot + 'config/config');

  module.exports.http = function(req, res, next) {
    if (req.url.indexOf(config.apiSubDir) === 0) {
      if (req.query && req.query.expand) {
        req.apiExpand = req.query.expand;
      }
      req.requestType = 'http';
      res.jsonAPIRespond = function(json) {
        if (json.code == null) {
          json.code = config.defaultCode;
        }
        return res.json(json.code, json);
      };
    }
    return next();
  };

  module.exports.socketio = function(req, res, callback) {
    var httpEmulatedRequest;
    httpEmulatedRequest = {
      requestType: 'socketio',
      method: !_.isUndefined(req.data.method) ? req.data.method : 'get',
      url: config.apiSubDir + (!_.isUndefined(req.data.url) ? req.data.url : '/'),
      headers: [],
      query: !_.isUndefined(req.data.query) ? req.data.query : {},
      body: !_.isUndefined(req.data.data) ? req.data.data : {}
    };
    _.extend(req, httpEmulatedRequest);
    if (!_.isUndefined(req.query) && !_.isUndefined(req.query.expand)) {
      req.apiExpand = req.query.expand;
    }
    res.jsonAPIRespond = function(json) {
      if (json.code == null) {
        json.code = config.defaultCode;
      }
      return req.io.respond(json);
    };
    return callback(req, res);
  };

}).call(this);
