// Generated by CoffeeScript 1.6.3
/*
  Serves up the HTML skeleton of our SPA
*/


(function() {
  var async, config, html_minifier;

  async = require('async');

  html_minifier = require('html-minifier');

  config = require(GLOBAL.appRoot + 'config/config');

  module.exports = function(app) {
    return app.get('/', function(req, res, next) {
      return async.map(['header', 'body', 'footer'], function(item, callback) {
        return res.render(item, {
          environment: config.env,
          assetHash: GLOBAL.assetHash
        }, function(err, html) {
          return callback(err, html);
        });
      }, function(err, results) {
        var head, html;
        html = results[1] + results[2];
        html = html_minifier.minify(html, {
          collapseWhitespace: true,
          removeComments: true
        });
        head = html_minifier.minify(results[0], {
          collapseWhitespace: true
        });
        html = head + html;
        return res.end(html);
      });
    });
  };

}).call(this);
