// Generated by CoffeeScript 1.6.3
(function() {
  var ORM, apiAuth, apiVerifyObjectProperties, async, config, insertHelper, sequelize, uuid, _;

  _ = require('underscore');

  async = require('async');

  uuid = require('node-uuid');

  config = require(GLOBAL.appRoot + 'config/config');

  apiVerifyObjectProperties = require(GLOBAL.appRoot + 'components/apiVerifyObjectProperties');

  apiAuth = require(GLOBAL.appRoot + 'components/apiAuth');

  ORM = require(GLOBAL.appRoot + 'components/oRM');

  insertHelper = require(GLOBAL.appRoot + 'components/insertHelper');

  sequelize = ORM.setup();

  module.exports = function(app) {
    var client, employee, revision, template;
    revision = ORM.model('revision');
    template = ORM.model('template');
    client = ORM.model('client');
    employee = ORM.model('employee');
    return app.post(config.apiSubDir + '/v1/revisions', function(req, res) {
      return async.series([
        function(callback) {
          return apiAuth(req, res, callback);
        }, function(callback) {
          var clientUid, employeeUid, insertMethod, userType;
          userType = req.session.user.type;
          clientUid = req.session.user.clientUid;
          employeeUid = req.session.user.uid;
          switch (userType) {
            case 'superAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, revision, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'changeSummary': function(val, objectKey, object, callback) {
                      if (_.isUndefined(val)) {
                        return callback(null, {
                          success: false,
                          message: {
                            changeSummary: 'required'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    },
                    'scope': function(val, objectKey, object, callback) {
                      if (_.isUndefined(val)) {
                        return callback(null, {
                          success: false,
                          message: {
                            scope: 'required'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      var testClientUid;
                      testClientUid = !_.isUndefined(object['clientUid']) ? object['clientUid'] : clientUid;
                      return callback(null, {
                        success: true,
                        transform: [objectKey, 'clientUid', testClientUid]
                      });
                      /*
                      if _.isUndefined val
                        callback null,
                          success: true
                          transform:  [objectKey, 'clientUid', clientUid]
                      
                      else
                        client.find(
                          where:
                            uid: val
                        ).success (resultClient) ->
                      
                          if resultClient
                            mapObj = {}
                            mapObj[resultClient.uid] = resultClient
                            callback null,
                              success:    true
                              uidMapping: mapObj
                              #transform:  [objectKey, 'clientUid', resultClient.uid]
                          else
                            callback null,
                              success: false
                              message:
                                clientUid: 'unknown'
                      */

                    },
                    'templateUid': function(val, objectKey, object, callback) {
                      var testClientUid;
                      if (_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            templateUid: 'required'
                          }
                        });
                        return;
                      }
                      testClientUid = !_.isUndefined(object['clientUid']) ? object['clientUid'] : clientUid;
                      return async.parallel([
                        function(callback) {
                          return client.find({
                            where: {
                              uid: testClientUid
                            }
                          }).success(function(resultClient) {
                            return callback(null, resultClient);
                          });
                        }, function(callback) {
                          return template.find({
                            where: {
                              uid: val
                            }
                          }).success(function(resultTemplate) {
                            return callback(null, resultTemplate);
                          });
                        }
                      ], function(error, results) {
                        var mapObj, resultClient, resultTemplate;
                        resultClient = results[0];
                        resultTemplate = results[1];
                        if (!resultTemplate) {
                          callback(null, {
                            success: false,
                            message: {
                              'templateUid': 'unknown'
                            }
                          });
                          return;
                        }
                        if (!resultClient) {
                          callback(null, {
                            success: false,
                            'clientUid': 'unknown'
                          });
                          return;
                        }
                        if (resultTemplate.clientUid !== resultClient.uid) {
                          callback(null, {
                            success: false,
                            message: {
                              'templateUid': 'unknown'
                            }
                          });
                          return;
                        }
                        mapObj = {};
                        mapObj[resultTemplate.uid] = resultTemplate;
                        mapObj[resultClient.uid] = resultClient;
                        return callback(null, {
                          success: true,
                          uidMapping: mapObj,
                          transform: [objectKey, 'clientUid', resultClient.uid]
                        });
                      });
                    }
                  }
                }, function(objects) {
                  return insertHelper('revisions', clientUid, revision, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return callback(null, createdUid);
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body);
              }
              break;
            case 'clientSuperAdmin':
            case 'clientAdmin':
              insertMethod = function(item, insertMethodCallback) {
                if (insertMethodCallback == null) {
                  insertMethodCallback = false;
                }
                return apiVerifyObjectProperties(this, revision, item, req, res, insertMethodCallback, {
                  requiredProperties: {
                    'changeSummary': function(val, objectKey, object, callback) {
                      if (_.isUndefined(val)) {
                        return callback(null, {
                          success: false,
                          message: {
                            changeSummary: 'required'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    },
                    'scope': function(val, objectKey, object, callback) {
                      if (_.isUndefined(val)) {
                        return callback(null, {
                          success: false,
                          message: {
                            scope: 'required'
                          }
                        });
                      } else {
                        return callback(null, {
                          success: true
                        });
                      }
                    },
                    'clientUid': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            clientUid: 'unknown'
                          }
                        });
                      } else {
                        return client.find({
                          where: {
                            uid: clientUid
                          }
                        }).success(function(resultClient) {
                          var mapObj;
                          mapObj = {};
                          mapObj[resultClient.uid] = resultClient;
                          return callback(null, {
                            success: true,
                            uidMapping: mapObj,
                            transform: [objectKey, 'clientUid', clientUid]
                          });
                        });
                      }
                    },
                    'templateUid': function(val, objectKey, object, callback) {
                      if (_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            templateUid: 'required'
                          }
                        });
                        return;
                      }
                      return async.parallel([
                        function(callback) {
                          return client.find({
                            where: {
                              uid: clientUid
                            }
                          }).success(function(resultClient) {
                            return callback(null, resultClient);
                          });
                        }, function(callback) {
                          return template.find({
                            where: {
                              uid: val
                            }
                          }).success(function(resultTemplate) {
                            return callback(null, resultTemplate);
                          });
                        }
                      ], function(error, results) {
                        var mapObj, resultClient, resultTemplate;
                        resultClient = results[0];
                        resultTemplate = results[1];
                        if (!resultTemplate) {
                          callback(null, {
                            success: false,
                            message: {
                              'templateUid': 'unknown'
                            }
                          });
                          return;
                        }
                        if (!resultClient) {
                          callback(null, {
                            success: false,
                            'clientUid': 'unknown'
                          });
                          return;
                        }
                        if (resultTemplate.clientUid !== resultClient.uid) {
                          callback(null, {
                            success: false,
                            message: {
                              'templateUid': 'unknown'
                            }
                          });
                          return;
                        }
                        mapObj = {};
                        mapObj[resultTemplate.uid] = resultTemplate;
                        mapObj[resultClient.uid] = resultClient;
                        return callback(null, {
                          success: true,
                          uidMapping: mapObj,
                          transform: [objectKey, 'clientUid', resultClient.uid]
                        });
                      });
                    },
                    'employeeUid': function(val, objectKey, object, callback) {
                      if (!_.isUndefined(val)) {
                        callback(null, {
                          success: false,
                          message: {
                            employeeUid: 'unknown'
                          }
                        });
                        return;
                      }
                      return async.parallel([
                        function(callback) {
                          return client.find({
                            where: {
                              uid: clientUid
                            }
                          }).success(function(resultClient) {
                            return callback(null, resultClient);
                          });
                        }, function(callback) {
                          return employee.find({
                            where: {
                              clientUid: clientUid,
                              uid: employeeUid
                            }
                          }).success(function(resultEmployee) {
                            return callback(null, resultEmployee);
                          });
                        }
                      ], function(error, results) {
                        var mapObj, resultClient, resultEmployee;
                        resultClient = results[0];
                        resultEmployee = results[1];
                        if (!resultEmployee) {
                          callback(null, {
                            success: false,
                            message: {
                              'employeeUid': 'unknown'
                            }
                          });
                          return;
                        }
                        if (!resultClient) {
                          callback(null, {
                            success: false,
                            'clientUid': 'unknown'
                          });
                          return;
                        }
                        if (resultEmployee.clientUid !== resultClient.uid) {
                          callback(null, {
                            success: false,
                            message: {
                              'employeeUid': 'unknown'
                            }
                          });
                          return;
                        }
                        mapObj = {};
                        mapObj[resultEmployee.uid] = resultEmployee;
                        mapObj[resultClient.uid] = resultClient;
                        return callback(null, {
                          success: true,
                          uidMapping: mapObj,
                          transform: [objectKey, 'employeeUid', resultEmployee.uid]
                        });
                      });
                    }
                  }
                }, function(objects) {
                  return insertHelper('revisions', clientUid, revision, objects, req, res, app, insertMethodCallback);
                });
              };
              if (_.isArray(req.body)) {
                return async.mapSeries(req.body, function(item, callback) {
                  return insertMethod(item, function(createdUid) {
                    return callback(null, createdUid);
                  });
                }, function(err, results) {
                  return config.apiSuccessPostResponse(res, results);
                });
              } else {
                return insertMethod(req.body);
              }
              break;
            case 'clientDelegate':
            case 'clientAuditor':
              return res.jsonAPIRespond(config.errorResponse(401));
          }
        }
      ]);
    });
  };

}).call(this);
